[package]
name = "users_canister"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
authentication = { path = "../../libraries/authentication" }
candid = "0.10"
canister_functions = { path = "../../libraries/canister_functions" }
currency = { git = "https://github.com/zk-game-dao/currency.git", branch = "main" }
errors = { path = "../../libraries/errors" }
ic-cdk = "0.12"
getrandom = { version = "0.2.15", features = ["custom"] }
thiserror = "1.0.57"
serde = { version = "1.0.197", features = ["derive"] }
lazy_static = "1.4.0"
ic-ledger-types = "0.10.0"
serde_bytes = "0.11.14"
sha2 = "0.10.8"
canistergeek_ic_rust = "0.4.3"
ic-stable-structures = "0.6.5"
user = { path = "../../libraries/user" }
ic-verifiable-credentials = "1.0.1"
ic-canister-sig-creation = "1.2.0"

[features]
default = []
test_default = []
