[package]
name = "errors"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.10.10"
serde = "1.0.208"
thiserror = "1.0.63"
currency = { git = "https://github.com/zk-game-dao/currency.git", branch = "main" }
