[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.10"
ic-cdk = "0.18.3"
ic-stable-structures = "0.6.5"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.63"
