[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-stable-structures = { workspace = true }
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.63"
