name: ZkPoker CI/CD Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "development" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Table Canister
        run: |
          cd src/table_canister
          rustup default stable
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown

      - name: Build User Canister
        run: |
          cd src/users_canister
          rustup default stable
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown

      - name: Build Tournament Canister
        run: |
          cd src/tournament_canister
          rustup default stable
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown

      - name: Run cargo clippy
        run: |
          rustup default stable
          rustup target add wasm32-unknown-unknown
          cargo clippy --verbose --all-targets -- -D warnings

  test-libraries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown

      - name: Build Table Canister
        working-directory: src/table_canister
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Build User Canister
        working-directory: src/users_canister
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Run cargo test for table library
        working-directory: libraries
        run: cargo test --verbose --package table

  test-end-to-end:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [
          "basic_tests",
          "cycle_tests",
          "deposit_tests",
          "fake_currency_tests",
          "filter_tests",
          "leaderboard",
          "pause_unpause_tests",
          "pot",
          "sitting_in_and_out_tests",
          "table_tests",
          "tournament_tests::addon_tests",
          "tournament_tests::basic_tests",
          "tournament_tests::cycle_tests",
          "tournament_tests::late_registration_tests",
          "tournament_tests::multi_table_tests",
          "tournament_tests::multiple_blind_level_tests",
          "tournament_tests::payouts",
          "tournament_tests::rebuy_tests",
          "upgrade_table_tests",
          "upgrade_tournament_tests",
          "turn_tests",
        ]
    steps:
      - uses: actions/checkout@v2

      - name: Build Table Canister
        run: |
          cd src/table_canister
          rustup default stable
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown

      - name: Build User Canister
        run: |
          cd src/users_canister
          rustup default stable
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown

      - name: Build User Index
        run: |
          cd src/users_index
          rustup default stable
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown

      - name: Build Table Index
        run: |
          cd src/table_index
          rustup default stable
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown
      
      - name: Build Tournament Canister
        run: |
          cd src/tournament_canister
          rustup default stable
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown
      
      - name: Build Tournament Index
        run: |
          cd src/tournament_index
          rustup default stable
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown

      - name: Run end to end tests for ${{ matrix.module }}
        run: |
          rustup default stable
          rustup target add wasm32-unknown-unknown
          ./scripts/run-tests.sh ${{ matrix.module }}

  test-ui:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with: 
          dfx-version: "0.24.2"

      - name: Install Rust and wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install dependencies
        run: npm i

      - name: Start replica
        run: dfx start --background

      - name: Generate candid declarations
        run: dfx deploy

      - run: npm ci

      - run: npm test
